#!/bin/bash

# Ha source paranccsal hivtak:
if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
	source /etc/dsInitd/templates/completion
	return 0
fi

exec /usr/bin/perl -x "$0" "$@"

#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use bytes;
use File::Basename qw(basename);
use File::Copy qw(copy);
use File::Spec;
use Fcntl qw(:flock);

my $BASE = '/etc/dsInitd';
my $DAEMONS = "$BASE/daemons";
my $TEMPLATES = "$BASE/templates";
my $DSI = "$BASE/inits";
my $SYS = "$BASE/init.d";
my $SYSTEM = '/etc/init.d';
my @ACTIONS = qw(start stop restart status show reshow);
my %ACTION = map { $_ => 1 } @ACTIONS;
my %LSB = (
	REQUIRED_START => ['Required-Start', '\$local_fs \$remote_fs'],
	REQUIRED_STOP => ['Required-Stop', '\$local_fs \$remote_fs'],
	SHOULD_START => ['Should-Start', '\$network'],
	SHOULD_STOP => ['Should-Stop', '\$network'],
	DEFAULT_START => ['Default-Start', '2 3 4 5'],
	DEFAULT_STOP => ['Default-Stop', '0 1 6'],
);
my %ALLOWED = map { $_ => 1 } (qw(PROCCESSCMD PROCCESSNAME RUNAS SHORTDESCRIPTION DESCRIPTION), keys %LSB);
my @NO_NAME = qw(dsinitd-enable dsinitd-disable dsinitd-status dsinitd-help completion);

sub fail
{
	my ($msg) = @_;
	die "HIBA: $msg\n";
}

sub name_check
{
	my ($name) = @_;
	defined($name) && $name =~ /\A[a-zA-Z0-9][a-zA-Z0-9_.-]*\z/ && $name !~ /\A\.\.?\z/
		or fail('ervenytelen szolgaltatasnev; csak betuk, szamok, pont, _ es - engedelyezett');
	return $name;
}

sub load_text
{
	my ($file) = @_;
	open my $fh, '<', $file or fail("nem olvashato: $file: $!");
	local $/;
	my $content = <$fh>;
	close $fh or fail("olvasasi hiba: $file: $!");
	return $content;
}

sub write_atomic
{
	my ($path, $content, $mode) = @_;
	my $temporary = "$path.tmp.$$";
	-e $temporary || -l $temporary and fail("utkozo ideiglenes fajl: $temporary");
	open my $fh, '>', $temporary or fail("nem irhato: $temporary: $!");
	my $printed = print {$fh} $content;
	my $closed = close($fh);
	my $permissions = chmod($mode, $temporary);
	if (!$printed || !$closed || !$permissions)
	{
		unlink $temporary;
		fail("nem sikerult kiirni: $path: $!");
	}
	rename $temporary, $path or do { unlink $temporary; fail("atnevezes sikertelen: $path: $!") };
}

sub shell_quote
{
	my ($value) = @_;
	$value =~ s/'/'"'"'/g;
	return "'$value'";
}

# Szandekosan csak literal egyszeres/kettos idezojeles ertekek; nincs shell eval.
# Tamogatja a tobb soros, egyszeres idezojeles parancsokat es a szokasos \-escape-eket.
sub parse_config
{
	my ($file, $name) = @_;
	my $src = load_text($file);
	my %config;
	pos($src) = 0;
	while (pos($src) < length($src))
	{
		$src =~ /\G[ \t]*(?:\#[^\n]*|\r?\n)/gc and next;
		$src =~ /\G[ \t]*([A-Z_]+)[ \t]*=[ \t]*/gc or fail("hibas konfiguracio: $file a(z) " . (1 + (() = substr($src, 0, pos($src)) =~ /\n/g)) . '. sor kornyeken');
		my $key = $1;
		$ALLOWED{$key} or fail("ismeretlen konfiguracios mezo: $key ($file)");
		!exists($config{$key}) or fail("ismetelt konfiguracios mezo: $key ($file)");
		my $quote;
		if ($src =~ /\G(['"])/gc) { $quote = $1; }
		else { fail("a(z) $key erteket idezojelbe kell tenni ($file)"); }
		my $value = '';
		my $closed = 0;
		while (pos($src) < length($src))
		{
			$src =~ /\G(.)/gcs or last;
			my $char = $1;
			if ($char eq $quote) { $closed = 1; last; }
			# A literal single-quoted konfiguracioban a backslash valtozatlan.
			# Dupla idezojelnel is literal: az LSB $local_fs nem shell valtozo.
			$value .= $char;
		}
		$closed or fail("lezaratlan idezojel: $key ($file)");
		$src =~ /\G[ \t]*(?:\#[^\n]*)?(?:\r?\n|\z)/gc or fail("szemet az ertek utan: $key ($file)");
		$config{$key} = $value;
	}
	defined($config{PROCCESSCMD}) && $config{PROCCESSCMD} =~ /\S/ && $config{PROCCESSCMD} ne 'ADD_COMMAND' or fail("hianyzo vagy kitoltetlen PROCCESSCMD: $file");
	$config{PROCCESSNAME} = $name unless defined($config{PROCCESSNAME}) && length($config{PROCCESSNAME});
	name_check($config{PROCCESSNAME});
	$config{PROCCESSNAME} eq $name or fail("PROCCESSNAME nem egyezik a fajlnevevel: $name");
	$config{RUNAS} = 'root' unless defined($config{RUNAS}) && length($config{RUNAS});
	$config{RUNAS} =~ /\A[a-z_][a-z0-9_-]*\$?\z/i or fail('ervenytelen RUNAS');
	defined(getpwnam($config{RUNAS})) or fail("nem letezo RUNAS felhasznalo: $config{RUNAS}");
	$config{SHORTDESCRIPTION} //= '';
	$config{DESCRIPTION} //= '';
	for my $key (keys %LSB, qw(SHORTDESCRIPTION DESCRIPTION))
	{
		next unless defined($config{$key});
		$config{$key} !~ /[\r\n\x00]/ or fail("tiltott vezerlokarakter: $key");
	}
	for my $key (qw(DEFAULT_START DEFAULT_STOP))
	{
		next unless exists $config{$key};
		$config{$key} =~ /\A[0-6](?:[ \t]+[0-6])*\z/ or fail("ervenytelen futasi szintek: $key");
	}
	for my $key (qw(REQUIRED_START REQUIRED_STOP SHOULD_START SHOULD_STOP))
	{
		next unless exists $config{$key};
		$config{$key} =~ /\A[a-zA-Z0-9_\$ .-]*\z/ or fail("ervenytelen fuggoseg: $key");
	}
	return \%config;
}

sub config_for
{
	my ($name) = @_;
	name_check($name);
	my $file = "$DAEMONS/$name";
	-f $file && !-l $file or fail("hianyzo vagy symlink daemon: $name");
	my @stat = stat($file);
	@stat && $stat[4] == 0 && !($stat[2] & 0022)
		or fail("nem biztonsagos tulajdonos/jogosultsag: $name (root tulajdon, nincs group/other iras)");
	return ($file, undef) if -x $file;
	return ($file, parse_config($file, $name));
}

sub validate_standalone
{
	my ($file, $name) = @_;
	my $src = load_text($file);
	$src =~ /\A\#\!\/bin\/sh\b/ or fail("standalone shebang hianyzik: $name");
	$src =~ /^\# Provides:\s*\Q$name\E\s*$/m or fail("standalone Provides nem egyezik: $name");
	$src =~ /### BEGIN INIT INFO/ && $src =~ /### END INIT INFO/ or fail("standalone LSB fejlec hianyzik: $name");
	$src !~ /PROCCESSCMD=['"]ADD_COMMAND['"]/ or fail("standalone parancs kitoltetlen: $name");
	system('/bin/sh', '-n', $file) == 0 or fail("standalone shell szintaktikai hiba: $name");
}

sub launcher_content
{
	my ($name, $cfg) = @_;
	my $text = load_text("$TEMPLATES/run-template");
	for my $k (keys %LSB)
	{
		my ($field) = @{$LSB{$k}};
		my $v = exists($cfg->{$k}) ? $cfg->{$k} : undef;
		next unless defined $v;
		$text =~ s/^(\# \Q$field\E:\s*).*$/"$1$v"/me or fail("run-template mezo hianyzik: $field");
	}
	my %replace = ( '__SERVICE_NAME__' => $name,
		'__SHORT_DESCRIPTION__' => $cfg->{SHORTDESCRIPTION},
		'__DESCRIPTION__' => $cfg->{DESCRIPTION});
	for my $placeholder (keys %replace)
	{
		my $value = $replace{$placeholder};
		$text =~ s/\Q$placeholder\E/$value/g;
	}
	$text =~ /^\# Provides:\s*\Q$name\E\s*$/m or fail('run-template Provides hiba');
	$text =~ /exec \Q$BASE\E\/dsinitctl "\$1" "\Q$name\E"/ or fail('run-template exec hiba');
	# shell -n stdin: nem irunk temp fajlt a validalashoz.
	open my $sh, '|-', '/bin/sh', '-n' or fail('shell ellenorzes nem indithato');
	print {$sh} $text;
	close($sh) or fail('general indito shell szintaktikai hiba');
	return $text;
}

sub runtime_content
{
	my ($name, $cfg) = @_;
	my $src = load_text("$TEMPLATES/standalone-template");
	my %replace = (
		'PROCCESSCMD' => shell_quote($cfg->{PROCCESSCMD}),
		'PROCCESSNAME' => shell_quote($name),
		'RUNAS' => shell_quote($cfg->{RUNAS}),
	);
	for my $key (keys %replace)
	{
		$src =~ s/^\Q$key\E=[^\n]*$/$key=$replace{$key}/m or fail("standalone-template mezo hianyzik: $key");
	}
	$src =~ s/^\# Provides:\s*TEMPLATE\s*$/"# Provides:          $name"/me or fail('standalone-template Provides hianyzik');
	open my $sh, '|-', '/bin/sh', '-n' or fail('shell ellenorzes nem indithato');
	print {$sh} $src;
	close($sh) or fail('general futtato shell szintaktikai hiba');
	return $src;
}

sub run_memory
{
	my ($src, $action) = @_;
	# pipe stdin a /bin/sh -s action reszere, a shell kod sosem kerul lemezre.
	my $pid = open(my $sh, '|-', '/bin/sh', '-s', '--', $action);
	defined($pid) or fail("nem indithato shell: $!");
	print {$sh} $src or fail("nem irhato a shell stdin: $!");
	close($sh);
	return $? == -1 ? 1 : ($? & 127 ? 128 + ($? & 127) : $? >> 8);
}

sub lock_registry
{
	open my $fh, '>>', "$BASE/.dsinitctl.lock" or fail("lock fajl nem nyithato: $!");
	flock($fh, LOCK_EX) or fail("lock hiba: $!");
	return $fh;
}

sub is_link_to
{
	my ($link, $target) = @_;
	return -l $link && readlink($link) eq $target;
}

sub link_safe
{
	my ($target, $link) = @_;
	if (-e $link || -l $link)
	{
		is_link_to($link, $target) or fail("idegen fajl vagy link: $link");
		return 0;
	}
	symlink($target, $link) or fail("symlink hiba: $link: $!");
	return 1;
}

sub unlink_safe
{
	my ($target, $link) = @_;
	return 0 unless -e $link || -l $link;
	is_link_to($link, $target) or fail("idegen fajl vagy link: $link");
	unlink($link) or fail("nem torolheto link: $link: $!");
	return 1;
}

sub sys_registered
{
	my ($name) = @_;
	return (-e "$SYS/$name" || -l "$SYS/$name" || -e "$SYSTEM/$name" || -l "$SYSTEM/$name");
}

sub dsi_registered
{
	my ($name) = @_;
	return -e "$DSI/$name" || -l "$DSI/$name";
}

sub update_rc
{
	my (@arguments) = @_;
	system('update-rc.d', @arguments) == 0 or fail('update-rc.d sikertelen: ' . join(' ', @arguments));
}

sub daemon_enable
{
	my ($mode, $name) = @_;
	my ($file, $cfg) = config_for($name);
	if ($mode eq 'dsi' && sys_registered($name)) { fail("$name mar SYS modban regisztralt; elobb disable-sys $name"); }
	if ($mode eq 'sys' && dsi_registered($name)) { fail("$name mar DSI modban regisztralt; elobb disable-dsi $name"); }
	my $src;
	if ($cfg)
	{
		# Az engedelyezes elott mindket generator teljes ellenorzese kotelezo.
		runtime_content($name, $cfg);
		$src = launcher_content($name, $cfg);
	}
	else { validate_standalone($file, $name); }
	my $folder = $mode eq 'sys' ? $SYS : $DSI;
	my $entry = "$folder/$name";
	my $system_link = "$SYSTEM/$name";
	if (-e $entry || -l $entry)
	{
		if ($cfg)
		{
			-l $entry and fail("idegen symlink: $entry");
			my $content = load_text($entry);
			$content =~ /^\# Provides:\s*\Q$name\E\s*$/m && $content =~ /exec \Q$BASE\E\/dsinitctl/ or fail("idegen indito: $entry");
		}
		else { is_link_to($entry, $file) or fail("idegen symlink: $entry"); }
		if ($mode eq 'sys')
		{
			is_link_to($system_link, $entry) or fail("nem teljes SYS regisztracio: $name");
		}
		print "$name: mar engedelyezve ($mode); nincs ujrageneralas.\n";
		return;
	}
	if ($mode eq 'sys' && (-e $system_link || -l $system_link)) { fail("idegen rendszerfajl: $system_link"); }
	if ($cfg) { write_atomic($entry, $src, 0755); }
	else { link_safe($file, $entry); }
	if ($mode eq 'sys')
	{
		my $created = 0;
		eval {
			$created = link_safe($entry, $system_link);
			update_rc($name, 'defaults');
			1;
		} or do {
			my $error = $@;
			unlink_safe($entry, $system_link) if $created;
			if ($cfg) { unlink($entry); }
			else { unlink_safe($file, $entry); }
			die $error;
		};
		system('systemctl', 'daemon-reload') if -d '/run/systemd/system';
	}
	print "$name: $mode engedelyezve.\n";
}

sub daemon_disable
{
	my ($mode, $name) = @_;
	name_check($name);
	my $file = "$DAEMONS/$name";
	my $folder = $mode eq 'sys' ? $SYS : $DSI;
	my $entry = "$folder/$name";
	my $system_link = "$SYSTEM/$name";
	if ($mode eq 'sys')
	{
		if (-e $system_link || -l $system_link)
		{
			is_link_to($system_link, $entry) or fail("idegen rendszerfajl: $system_link");
			update_rc('-f', $name, 'remove');
			unlink_safe($entry, $system_link);
		}
		elsif (-e $entry || -l $entry) { fail("hianyzo rendszerlink: $system_link; nem toroljuk a reszleges regisztraciot"); }
	}
	if (-e $entry || -l $entry)
	{
		if (-l $entry) { unlink_safe($file, $entry); }
		else
		{
			-f $entry && -f $file && !-x $file or fail("nem sajat generalt indito: $entry");
			my $content = load_text($entry);
			$content =~ /^\# Provides:\s*\Q$name\E\s*$/m && $content =~ /exec \Q$BASE\E\/dsinitctl/ or fail("nem felismerheto generalt indito: $entry");
			unlink($entry) or fail("nem torolheto: $entry: $!");
		}
	}
	system('systemctl', 'daemon-reload') if $mode eq 'sys' && -d '/run/systemd/system';
	print "$name: $mode letiltva (futo folyamat erintetlen).\n";
}

sub auto_enable
{
	my $target = "$TEMPLATES/dsInitd-auto";
	my $marker = "$TEMPLATES/dsInitd-auto.enabled";
	my $syslink = "$SYSTEM/dsInitd-auto";
	-f $target && -x $target or fail('dsInitd-auto nem futtathato');
	my $created_marker = link_safe($target, $marker);
	my $created_sys = 0;
	eval {
		$created_sys = link_safe($marker, $syslink);
		update_rc('dsInitd-auto', 'defaults');
		1;
	} or do {
		my $error = $@;
		unlink_safe($marker, $syslink) if $created_sys;
		unlink_safe($target, $marker) if $created_marker;
		die $error;
	};
	system('systemctl', 'daemon-reload') if -d '/run/systemd/system';
	print "dsInitd-auto engedelyezve.\n";
}

sub auto_disable
{
	my $target = "$TEMPLATES/dsInitd-auto";
	my $marker = "$TEMPLATES/dsInitd-auto.enabled";
	my $syslink = "$SYSTEM/dsInitd-auto";
	if (-e $syslink || -l $syslink)
	{
		is_link_to($syslink, $marker) or fail("idegen rendszerlink: $syslink");
		update_rc('-f', 'dsInitd-auto', 'remove');
		unlink_safe($marker, $syslink);
	}
	unlink_safe($target, $marker);
	system('systemctl', 'daemon-reload') if -d '/run/systemd/system';
	print "dsInitd-auto letiltva (futo folyamat erintetlen).\n";
}

# Teljes eltavolitas: csak sajat bejegyzeseket erint, es a stop kotelezo.
sub daemon_remove
{
	my ($name) = @_;
	my ($file, $cfg) = config_for($name);
	my $dsi = dsi_registered($name);
	my $sys = sys_registered($name);
	my $sys_entry = "$SYS/$name";
	my $dsi_entry = "$DSI/$name";
	my $system_link = "$SYSTEM/$name";
	# Minden objektumot elore validalunk, mielott a folyamatot megallitjuk.
	if ($sys)
	{
		(-l $system_link && is_link_to($system_link, $sys_entry))
			or fail("hianyzo vagy idegen /etc/init.d bejegyzes: $name");
	}
	for my $entry (($dsi ? ($dsi_entry) : ()), ($sys ? ($sys_entry) : ()))
	{
		if ($cfg)
		{
			-f $entry && !-l $entry or fail("idegen indito: $entry");
			my $src = load_text($entry);
			$src =~ /^\# Provides:\s*\Q$name\E\s*$/m &&
			$src =~ /exec \Q$BASE\E\/dsinitctl "\$1" "\Q$name\E"/
				or fail("nem felismerheto dsInit indito: $entry");
		}
		else { is_link_to($entry, $file) or fail("idegen standalone link: $entry"); }
	}
	my $rc = $cfg ? run_memory(runtime_content($name, $cfg), 'stop') : do
	{
		system($file, 'stop');
		$? == -1 ? 1 : ($? & 127 ? 128 + ($? & 127) : $? >> 8);
	};
	$rc == 0 or fail("leallitas sikertelen ($rc); nem toroljuk: $name");
	# A status nem lehet 0 (fut) vagy 1 (hiba); csak a 3 igazolja a leallast.
	my $status = $cfg ? run_memory(runtime_content($name, $cfg), 'status') : do
	{
		system($file, 'status');
		$? == -1 ? 1 : ($? & 127 ? 128 + ($? & 127) : $? >> 8);
	};
	$status == 3 or fail("a leallas nem igazolhato (status=$status): $name");
	daemon_disable('dsi', $name) if $dsi;
	daemon_disable('sys', $name) if $sys;
	unlink($file) or fail("nem torolheto a daemon fajl: $file: $!");
	print "$name: leallitva, regisztraciok es daemon torolve.\n";
}

sub daemon_names
{
	opendir(my $dir, $DAEMONS) or fail("daemons nem olvashato: $!");
	my @names = sort grep { $_ !~ /^\./ && -f "$DAEMONS/$_" && !-l "$DAEMONS/$_" } readdir($dir);
	closedir($dir);
	return @names;
}

sub runlevels
{
	my ($name) = @_;
	my @levels;
	for my $level (0 .. 6)
	{
		my @links = glob("/etc/rc$level.d/S[0-9][0-9]$name");
		push @levels, $level if grep { -l $_ } @links;
	}
	return @levels ? join(',', @levels) : '-';
}

# Az allapotjelentes nem inditja el es nem allitja le a szolgaltatast.
# A Screen sajat munkamenetlistajabol vizsgalja a tenyleges futast.
sub daemon_running
{
	my ($name, $file) = @_;
	return 'UNKNOWN' unless -x '/usr/bin/screen' || system('/bin/sh', '-c', 'command -v screen >/dev/null 2>&1') == 0;
	my ($user, $session) = ('root', $name);
	if (-x $file)
	{
		my $src = eval { load_text($file) };
		return 'ERROR' if $@;
		$user = $1 if $src =~ /^RUNAS=["']([a-zA-Z_][a-zA-Z0-9_-]*)["']\s*$/m;
		$session = $1 if $src =~ /^SESSION=["']([^"'\r\n]+)["']\s*$/m && $1 !~ /\$/;
	}
	else
	{
		my $cfg = eval { parse_config($file, $name) };
		return 'ERROR' if $@;
		$user = $cfg->{RUNAS};
	}
	return 'ERROR' unless defined getpwnam($user);
	my @command = $user eq 'root' ? ('screen', '-ls') : ('runuser', '-u', $user, '--', 'screen', '-ls');
	open my $output, '-|', @command or return 'UNKNOWN';
	my $running = 0;
	while (my $line = <$output>)
	{
		if ($line =~ /^\s*([0-9]+)\.([^\s]+)\s/ && $2 eq $session)
		{
			$running = 1;
		}
	}
	close $output;
	return $running ? 'YES' : 'NO';
}

sub full_status
{
	my $marker = "$TEMPLATES/dsInitd-auto.enabled";
	print 'Centralis dsInitd: ', is_link_to($marker, "$TEMPLATES/dsInitd-auto") ? 'ENABLED' : 'DISABLED', "\n";
	printf "%-36s %-12s %-8s %-8s %-10s %-8s %-8s\n", qw(DAEMON TYPE DSI SYS RUNLEVELS SYSTEM RUNNING);
	for my $name (daemon_names())
	{
		my $file = "$DAEMONS/$name";
		my $dsi = dsi_registered($name) ? 'YES' : 'NO';
		my $sys = sys_registered($name) ? 'YES' : 'NO';
		my $system = is_link_to("$SYSTEM/$name", "$SYS/$name") ? 'OK' : ($sys eq 'YES' ? 'MISSING' : '-');
		printf "%-36s %-12s %-8s %-8s %-10s %-8s %-8s\n", $name, (-x $file ? 'standalone' : 'dsInit'), $dsi, $sys, runlevels($name), $system, daemon_running($name, $file);
	}
}

sub create_daemon
{
	my ($type, $name) = @_;
	name_check($name);
	my $template = $type eq 'standalone' ? "$TEMPLATES/standalone-template" : "$TEMPLATES/dsInit-template";
	my $destination = "$DAEMONS/$name";
	-e $destination || -l $destination and fail("mar letezik: $destination");
	my $src = load_text($template);
	if ($type eq 'standalone')
	{
		$src =~ s/^\# Provides:\s*TEMPLATE\s*$/"# Provides:          $name"/me or fail('Provides sablonsor nem talalhato');
	}
	$src =~ s/^PROCCESSNAME="TEMPLATE"$/"PROCCESSNAME=\"$name\""/me or fail('PROCCESSNAME sablonsor nem talalhato');
	write_atomic($destination, $src, $type eq 'standalone' ? 0755 : 0644);
	print "Letrehozva: $destination\n";
	if (-t 0 && -t 1)
	{
		system('nano', $destination) == 0 or fail('nano sikertelen; automatikus engedelyezes kihagyva');
		print "Engedelyezzem? dsinitctl enable $name [y/N] ";
		my $answer = <STDIN> // '';
		if ($answer =~ /\A\s*(?:y|yes|i|igen)\s*\z/i)
		{
			dispatch('enable', $name);
		}
	}
	else { print "Nem interaktiv terminal: nano es engedelyezesi kerdes kihagyva.\n"; }
}

sub root_required
{
	$> == 0 or fail('root jogosultsag szukseges (sudo)');
}

sub page_text
{
	my ($text) = @_;
	if (-t STDOUT && -t STDIN && system('sh', '-c', 'command -v less >/dev/null 2>&1') == 0)
	{
		open my $pager, '|-', 'less', '-R' or fail('less nem indithato');
		print {$pager} $text;
		close($pager) or fail('less hibaval lepett ki');
	}
	else { print $text; }
}

sub short_help
{
	print <<'HELP';
dsInitd V0.2.2 – vezerlo
Usage: dsinitctl PARANCS [DAEMON]
start stop restart status show reshow
 enable disable enable-dsi enable-sys disable-dsi disable-sys
 create-standalone (cs) create-dsInit (cd) help man edit read remove
 dsinitd-enable dsinitd-disable dsinitd-status dsinitd-help completion
Dokumentacio: perldoc /etc/dsInitd/dsinitctl
A show/reshow interaktiv: Ctrl+A, majd D = levalasztas.
HELP
}

sub dispatch
{
	my ($cmd, $name) = @_;
	defined($cmd) or do { short_help(); return 2; };
	if ($cmd eq 'dsinitd-help') { short_help(); return 0; }
	if ($cmd eq 'completion')
	{
		defined($name) and fail('completion nem fogad parametert');
		print 'source dsinitctl', "\n";
		print STDERR 'Az aktualis Bash terminalban: source dsinitctl', "\n" if -t STDERR;
		return 0;
	}
	if ($cmd eq 'dsinitd-status') { defined($name) and fail('nincs masodik parameter'); full_status(); return 0; }
	if ($cmd eq 'dsinitd-enable' || $cmd eq 'dsinitd-disable')
	{
		defined($name) and fail('nincs masodik parameter');
		root_required();
		my $lock = lock_registry();
		$cmd eq 'dsinitd-enable' ? auto_enable() : auto_disable();
		return 0;
	}
	defined($name) or fail("kotelezo a daemon neve: $cmd");
	name_check($name);
	if ($cmd eq 'create-standalone' || $cmd eq 'cs' || $cmd eq 'create-dsInit' || $cmd eq 'cd')
	{
		root_required();
		create_daemon($cmd eq 'create-standalone' || $cmd eq 'cs' ? 'standalone' : 'dsInit', $name);
		return 0;
	}
	if ($cmd eq 'remove')
	{
		root_required();
		my $lock = lock_registry();
		daemon_remove($name);
		return 0;
	}
	if ($cmd =~ /\A(?:enable|disable)(?:-(?:dsi|sys))?\z/)
	{
		root_required();
		my $lock = lock_registry();
		my $mode = $cmd =~ /-(dsi|sys)\z/ ? $1 : is_link_to("$TEMPLATES/dsInitd-auto.enabled", "$TEMPLATES/dsInitd-auto") ? 'dsi' : 'sys';
		$cmd =~ /^enable/ ? daemon_enable($mode, $name) : daemon_disable($mode, $name);
		return 0;
	}
	my ($file, $cfg) = config_for($name);
	if ($cmd eq 'edit')
	{
		root_required();
		system('nano', $file) == 0 or fail('nano sikertelen');
		print "Mentve. A mar generalt inditok NEM frissulnek.\n";
		return 0;
	}
	if ($cmd eq 'read')
	{
		if ($cfg) { print runtime_content($name, $cfg); }
		else { page_text(load_text($file)); }
		return 0;
	}
	if ($cmd eq 'help' || $cmd eq 'man')
	{
		if ($cfg) { print(($cmd eq 'help' ? $cfg->{SHORTDESCRIPTION} : $cfg->{DESCRIPTION}), "\n"); }
		else { page_text(load_text($file)); }
		return 0;
	}
	$ACTION{$cmd} or fail("ismeretlen parancs: $cmd (dsinitctl dsinitd-help)");
	if ($cfg)
	{
		root_required() unless $cmd eq 'status';
		return run_memory(runtime_content($name, $cfg), $cmd);
	}
	system($file, $cmd);
	return $? == -1 ? 1 : ($? & 127 ? 128 + ($? & 127) : $? >> 8);
}

my $exit = eval { @ARGV <= 2 or fail('tul sok parameter'); dispatch(@ARGV) };
if ($@) { print STDERR $@; exit 1; }
exit($exit // 0);

__END__

=encoding utf8

=head1 NAME

dsinitctl - dsInitd Perl alapú szolgáltatásvezérlő

=head1 SYNOPSIS

  sudo /etc/dsInitd/dsinitctl create-dsInit mydaemon
  sudo /etc/dsInitd/dsinitctl enable-sys mydaemon
  sudo /etc/dsInitd/dsinitctl start mydaemon
  sudo /etc/dsInitd/dsinitctl status mydaemon
  sudo /etc/dsInitd/dsinitctl dsinitd-status

=head1 DESCRIPTION

A dsInitd kétféle daemonformátumot kezel.

A C<daemons/> könyvtárban található futtatható fájlok önálló,
SysV-kompatibilis shell scriptek.

A nem futtatható fájlok dsInit konfigurációk. Ezekből a
C<dsinitctl> a C<standalone-template> alapján futás közben,
memóriában állítja elő a teljes shell scriptet.

A dinamikusan összeállított futtatószkript nem kerül tartósan
lemezre.

=head1 DIRECTORY STRUCTURE

  /etc/dsInitd/dsinitctl

  /etc/dsInitd/daemons/
  /etc/dsInitd/inits/
  /etc/dsInitd/init.d/

  /etc/dsInitd/templates/standalone-template
  /etc/dsInitd/templates/dsInit-template
  /etc/dsInitd/templates/run-template
  /etc/dsInitd/templates/dsInitd-auto
  /etc/dsInitd/templates/dsInitd-auto.enabled
  /etc/dsInitd/templates/completion
  /etc/dsInitd/templates/install
  /etc/dsInitd/templates/test-standalone
  /etc/dsInitd/templates/test-dsInit

A C<dsInitd-auto.enabled> csak akkor létezik, ha a központi
DSI automatikus indítás engedélyezve van.

=head1 COMMANDS

=head2 Szolgáltatáskezelés

  start NAME
  stop NAME
  restart NAME
  status NAME
  show NAME
  reshow NAME

A futtatható standalone daemon közvetlenül megkapja az akciót
első argumentumként.

dsInit konfiguráció esetén a C<dsinitctl> memóriában előállítja
a teljes futtatószkriptet, majd végrehajtja a megadott műveletet.

A C<show> csatlakozik a szolgáltatáshoz tartozó GNU Screen
munkamenethez.

A Screen munkamenetről leválás:

  Ctrl+A, majd D

A C<reshow> először újraindítja a szolgáltatást, majd csatlakozik
a Screen munkamenethez.

=head2 Regisztráció

  enable NAME
  disable NAME

  enable-dsi NAME
  disable-dsi NAME

  enable-sys NAME
  disable-sys NAME

A SYS és DSI regisztráció kölcsönösen kizárja egymást.

Egy daemon nem lehet egyszerre mindkét módban engedélyezve.

=head3 DSI mód

DSI módban a szolgáltatás indítója a következő könyvtárba kerül:

  /etc/dsInitd/inits/

A központi C<dsInitd-auto> rendszerindításkor ezeket a
szolgáltatásokat kezeli.

=head3 SYS mód

SYS módban az indító a következő könyvtárba kerül:

  /etc/dsInitd/init.d/

Innen abszolút szimbolikus link mutat a következő helyre:

  /etc/init.d/

A szolgáltatást az C<update-rc.d> regisztrálja a Debian
futási szintjeihez.

dsInit konfiguráció esetén a DSI és SYS indítók is külön,
generált fájlok, saját LSB fejléccel.

A már generált indítók később nem frissülnek automatikusan
a template vagy a konfiguráció megváltoztatásakor.

A C<disable>, C<disable-dsi> és C<disable-sys> műveletek
nem állítják le az éppen futó szolgáltatást.

=head3 Automatikus módválasztás

Az egyszerű:

  enable NAME

és:

  disable NAME

parancs a C<dsInitd-auto.enabled> állapota alapján választ módot.

Ha a központi dsInitd automatikus indítás aktív, akkor DSI módot
használ.

Ellenkező esetben SYS módot használ.

=head2 Létrehozás

  create-standalone NAME
  cs NAME

  create-dsInit NAME
  cd NAME

A C<create-standalone> és rövidített C<cs> parancs a
C<standalone-template> fájlból hoz létre teljes, futtatható
standalone daemont.

A C<create-dsInit> és rövidített C<cd> parancs a
C<dsInit-template> alapján hoz létre nem futtatható dsInit
konfigurációt.

A létrehozott daemon neve bekerül a megfelelő konfigurációs
mezőkbe.

Interaktív terminál esetén a program a létrehozott fájlt
C<nano> szerkesztőben megnyitja, majd felajánlja az
engedélyezést.

Nem interaktív futás esetén a szerkesztés és az automatikus
engedélyezési kérdés kimarad.

=head2 Információ és szerkesztés

  help NAME
  man NAME
  read NAME
  edit NAME

dsInit konfiguráció esetén:

=over 4

=item C<help>

A C<SHORTDESCRIPTION> mezőt írja ki.

=item C<man>

A C<DESCRIPTION> mezőt írja ki.

=item C<read>

Kiírja a memóriában összeállított teljes futtatószkriptet.

=item C<edit>

Megnyitja az eredeti daemon konfigurációt C<nano> szerkesztőben.

=back

Standalone daemon esetén a C<help>, C<man> és C<read> a teljes
standalone fájlt jeleníti meg.

=head2 Daemon eltávolítása

  remove NAME

A C<remove> művelet:

=over 4

=item 1.

Leállítja a szolgáltatást.

=item 2.

Ellenőrzi, hogy a szolgáltatás ténylegesen leállt-e.

=item 3.

Eltávolítja a DSI és/vagy SYS regisztrációt.

=item 4.

Törli a daemon fájlját a C<daemons/> könyvtárból.

=back

Ha a leállítás sikertelen, vagy nem igazolható, a daemon nem
kerül törlésre.

A program idegen fájlt vagy ismeretlen eredetű init scriptet
nem töröl.

=head2 Központi dsInitd kezelés

  dsinitd-enable
  dsinitd-disable
  dsinitd-status
  dsinitd-help

A C<dsinitd-enable> létrehozza a következő jelző symlinket:

  /etc/dsInitd/templates/dsInitd-auto.enabled

A link a következő fájlra mutat:

  /etc/dsInitd/templates/dsInitd-auto

Ezután létrejön a központi SysV regisztráció is:

  /etc/init.d/dsInitd-auto

A szolgáltatás az C<update-rc.d> segítségével kerül
rendszerindításra regisztrálásra.

A C<dsinitd-disable> eltávolítja ezt a regisztrációt és a
jelző symlinket.

A már futó daemonokat a C<dsinitd-disable> nem állítja le.

A C<dsinitd-status> listázza az összes daemon főbb állapotát,
beleértve:

=over 4

=item *

daemon típusát

=item *

DSI regisztrációt

=item *

SYS regisztrációt

=item *

SysV futási szinteket

=item *

C</etc/init.d> rendszerlink állapotát

=item *

tényleges futási állapotot

=back

=head1 CONFIGURATION

A dsInit daemon nem futtatható konfigurációs fájl.

A konfiguráció a következő formát használja:

  KEY='érték'

vagy:

  KEY="érték"

A konfigurációs értékeket a C<dsinitctl> literálisan dolgozza fel.
A konfiguráció beolvasása nem hajt végre shell parancsokat.

A C<PROCCESSCMD> tartalma csak a daemon tényleges indításakor
kerül shellként végrehajtásra.

=head2 Kötelező mező

  PROCCESSCMD

A mezőnek érvényes parancsot kell tartalmaznia.

Az C<ADD_COMMAND> érték kitöltetlen sablonnak számít és nem
engedélyezhető.

=head2 Opcionális mezők

  PROCCESSNAME
  RUNAS
  SHORTDESCRIPTION
  DESCRIPTION

  REQUIRED_START
  REQUIRED_STOP
  SHOULD_START
  SHOULD_STOP
  DEFAULT_START
  DEFAULT_STOP

Ha a C<PROCCESSNAME> hiányzik, a daemon fájlneve lesz az
alapértelmezett érték.

Ha meg van adva, egyeznie kell a daemon fájlnevével.

A C<RUNAS> alapértelmezett értéke:

  root

A C<SHORTDESCRIPTION> és C<DESCRIPTION> alapértelmezés szerint
üres.

A hiányzó LSB mezők alapértékeit a C<run-template> biztosítja.

A C<Provides> értéke mindig a daemon neve.

=head1 LSB INIT INFORMATION

A dsInit konfiguráció az alábbi LSB mezőket írhatja felül:

  REQUIRED_START
  REQUIRED_STOP
  SHOULD_START
  SHOULD_STOP
  DEFAULT_START
  DEFAULT_STOP

Példa:

  REQUIRED_START='$local_fs $remote_fs'
  REQUIRED_STOP='$local_fs $remote_fs'
  SHOULD_START='$network'
  SHOULD_STOP='$network'
  DEFAULT_START='2 3 4 5'
  DEFAULT_STOP='0 1 6'

Ezekből a generált indító például a következő LSB mezőket
állítja elő:

  # Required-Start:    $local_fs $remote_fs
  # Required-Stop:     $local_fs $remote_fs
  # Should-Start:      $network
  # Should-Stop:       $network
  # Default-Start:     2 3 4 5
  # Default-Stop:      0 1 6

=head1 STANDALONE WITHOUT DSINITCTL

A standalone szolgáltatás a C<dsinitctl> használata nélkül is
telepíthető.

Másold le a standalone sablont:

  sudo cp /etc/dsInitd/templates/standalone-template /etc/init.d/mydaemon

Szerkeszd:

  sudo nano /etc/init.d/mydaemon

A fájlban legalább a következőket kell beállítani:

  # Provides:          mydaemon
  PROCCESSNAME="mydaemon"
  PROCCESSCMD='valódi parancs'

Ezután:

  sudo chmod 755 /etc/init.d/mydaemon
  sudo update-rc.d mydaemon defaults
  sudo systemctl daemon-reload

Indítás:

  sudo /etc/init.d/mydaemon start

Állapot:

  sudo /etc/init.d/mydaemon status

Leállítás:

  sudo /etc/init.d/mydaemon stop

Automatikus indítás megszüntetése:

  sudo update-rc.d -f mydaemon remove

A script törlése:

  sudo rm -- /etc/init.d/mydaemon
  sudo systemctl daemon-reload

Az C<update-rc.d remove> csak a rendszerindítási regisztrációt
távolítja el. A már futó szolgáltatást külön le kell állítani.

=head1 INSTALLATION

A dsInitd közvetlenül GitHubról is telepíthető:

  wget -qO- https://raw.githubusercontent.com/novarobot/dsInitd/main/templates/install | sudo bash

A bootstrap telepítő szükség esetén telepíti a Git és GNU Screen
csomagokat, majd letölti a repository-t és telepíti a rendszert
a következő helyre:

  /etc/dsInitd

A Git repository metaadatai, például a C<.git> könyvtár, nem
kerülnek a telepített rendszerbe.

A telepítő beállítja a szükséges futtatási jogokat és
felajánlja:

=over 4

=item *

a C</sbin/dsinitctl> symlink létrehozását;

=item *

a Bash TAB-kiegészítés telepítését;

=item *

a központi dsInitd automatikus rendszerindítás engedélyezését.

=back

=head1 BASH COMPLETION

A C<dsinitctl> Bash/Perl polyglot fájl.

Az aktuális Bash munkamenetben a TAB-kiegészítés közvetlenül
betölthető:

  source dsinitctl

A completion definíció helye:

  /etc/dsInitd/templates/completion

Telepítés esetén a következő symlink mutat erre:

  /usr/share/bash-completion/completions/dsinitctl

A TAB-kiegészítés támogatja a C<dsinitctl> parancsokat és a
C<daemons/> könyvtárban található daemonneveket.

=head1 FILE PERMISSIONS

A standalone daemonok futtatható fájlok.

A dsInit konfigurációk nem futtatható fájlok.

A daemon definícióknak root tulajdonban kell lenniük, és
group/other írási jogosultság nem megengedett.

A telepítő a szükséges futtatási jogokat automatikusan beállítja
a következő fő fájlokra:

  /etc/dsInitd/dsinitctl
  /etc/dsInitd/templates/install
  /etc/dsInitd/templates/dsInitd-auto
  /etc/dsInitd/templates/standalone-template

=head1 EXIT STATUS

A C<dsinitctl> általános visszatérési értékei:

  0   sikeres végrehajtás
  1   validációs, telepítési vagy szolgáltatáshiba
  2   hibás használat vagy hiányzó paraméter
  3   a szolgáltatás nem fut

Szolgáltatáskezelési műveleteknél a program lehetőség szerint
továbbítja az adott daemon saját visszatérési kódját.

=head1 SECURITY

A rendszerállapotot módosító műveletekhez root jogosultság
szükséges.

A C<dsinitctl> nem ír felül idegen fájlokat és ismeretlen
szimbolikus linkeket.

A dsInit konfiguráció C<PROCCESSCMD> mezője shell parancsot
tartalmaz, ezért a daemon konfigurációs fájlok csak megbízható,
root által felügyelt helyen tárolhatók.

A program ellenőrzi a daemon fájlok tulajdonosát és
jogosultságait.

A GNU Screen háttérindításához a kisbetűs C<-dm> kapcsoló
használatos.

A C<-Dm> kapcsoló egyes környezetekben blokkolhatja a hívó
terminált, ezért azt a dsInitd nem használja.

=head1 SEE ALSO

  perldoc /etc/dsInitd/dsinitctl

  screen(1)
  update-rc.d(8)
  systemctl(1)

=cut
