#!/bin/sh
### BEGIN INIT INFO
# Provides:          __SERVICE_NAME__
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: __SHORT_DESCRIPTION__
# Description:       __DESCRIPTION__
### END INIT INFO

exec /etc/dsInitd/dsinitctl "$1" "__SERVICE_NAME__"
